---
title: "Biological mechanisms are necessary to improve the robustness of species distribution models"
subtitle: "Figures for manuscript and extended data"
author: "V. Van der Meersch et al."
geometry: "left=1cm,right=1cm,top=1cm,bottom=1cm"
output: 
  pdf_document:
    keep_tex: true
header-includes:
  \pagenumbering{gobble}
  \usepackage{float}
  \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
wd <- "C:/Users/vandermeersch/Documents/CEFE/projects/past_robustness"

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      results='hide', fig.path= paste0(wd, "/manuscript/figs/files/"), fig.pos = 'H')
library(chunkhooks)
hook_figure_unit("mm")

source(file.path(wd, "manuscript", "processing", "setup.R"))
```

# Main

```{r climatic_dissimilarity, fig.height = 60, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Evolution of climatic dissimilarity under past (12k-500 yr BP) and future (2005-2100) climate changes, relative to 1901-2000}.", eval = T}
source(file.path(wd, "manuscript", "figs", "fig1", "main.R"))
fig1_main
```

\newpage

```{r process_model_outputs, include = F, eval = T}
source(file.path(wd, "manuscript", "processing", "model_simulations.R"))
source(file.path(wd, "manuscript", "processing", "model_transferability.R"))

# model_performance_relchg <- readRDS("C:/Users/vandermeersch/Documents/CEFE/projects/past_robustness/manuscript/processing/output/model_performance_relchg.rds")
# model_performance_withmig<- readRDS( "C:/Users/vandermeersch/Documents/CEFE/projects/past_robustness/manuscript/processing/output/model_performance_withmig.rds")
model_performance_withmig$clim_hpv_sorensen.mean <- 1-model_performance_withmig$clim_hpv_sorensen.mean # dissimilarity
```

```{r quercus_deciduous_simulations, fig.height = 240, fig.width = 122, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Example of paleosimulations obtained with the eight models used in this study for deciduous oaks.", eval = T}

source(file.path(wd, "manuscript", "figs", "fig2", "main2.R")) 
fig2_main

```

\newpage

```{r past_performance, fig.height = 120, fig.width = 190, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Performance of correlative models, fitted process-based models (inverse calibration using occurrence data) and expert process-based models (classical calibration) against Holocene paleoecogical evidence (fossil pollen) for 4 tree genera.", eval = F}

source(file.path(wd, "manuscript", "processing", "ordered_beta_regression.R"))

source(file.path(wd, "manuscript", "figs", "fig3", "beta_regression.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "boxplot_performance.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "boxplot_variance.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "boxplot_transferability.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "main2.R"))
fig3_main

```

\newpage

# Supplementary data

\renewcommand{\thefigure}{S\arabic{figure}}
\setcounter{figure}{0}

```{r figS1_climate_overview, fig.height = 105, fig.width = 180, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Chronology of past climate across the Late Pleistocene and the Holocene.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS1.R"))
figS1_main

```

```{r figS2_climatic_dissimilarity_novelty, fig.height = 90, fig.width = 200, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Evoltion of climatic dissimilarity/novelty in past and future.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS2.R"))
figS2_main

```

```{r figS3_hypervolume_representation, fig.height = 80, fig.width = 160, dev=c('ragg_png'), dpi = 400, fig.cap = "Climatic hypervolumes for Early Holocene period (dark and light blue, respectively 12000 BP and 11500 BP) and 2090 projections (orange and red, respectively SSP2 and SSP5 scenarios), as compared to historical period (green, 1901-2000).", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS3.R"))
figS3_main

```


```{r figs4_fagus_simulations, fig.height = 240, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Example of paleosimulations obtained with the eight models used in this study for beeches.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS4.R")) 
figS4_main

```

```{r figS5_abies_simulations, fig.height = 240, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Example of paleosimulations obtained with the eight models used in this study for firs.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS5.R")) 
figS5_main

```

```{r figS6_quercusevergreen_simulations, fig.height = 240, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Example of paleosimulations obtained with the eight models used in this study for evergreen oaks.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS6.R")) 
figS6_main

```

```{r figS7_migration_process_stochasticity, fig.height = 100, fig.width = 180, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Illustration of migration process and evaluation of the impact of migration process stochasticity.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS7", "migration_process.R"))

source(file.path(wd, "manuscript", "figs", "suppmat", "figS7", "migration_stochasticity.R"))

plot_grid(figS7_migration_process , figS7_migration_stochasticity, 
          ncol = 2, 
          rel_widths = c(0.43, 0.53), vjust = 1,
          labels = c("a", "b"), label_fontfamily = "Helvetica Narrow", label_size = 11)

```

```{r figS8_historical_performances, fig.height = 65, fig.width = 140, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Model performance in historical conditions.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figS8.R")) 
figS8_main
```

```{r figS9_performance_perspecies, fig.height = 100, fig.width = 195, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Impacts of migration on model performance, per species.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figS9.R")) 
figS9_main
```

```{r past_performance_wtime, eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "linear_plateau_regression.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10","performance_wtime.R")) 

```

```{r past_performance_TSS, eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "ordered_beta_regression_withTSS.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "beta_regression_withTSS.R"))

```

```{r past_performance_nomigration, eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "ordered_beta_regression_womigration.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "beta_regression_nomigration.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "boxplot_performance_nomigration.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "performance_nomigration.R"))

```

```{r past_performance_from11750, fig.height = 120, fig.width = 190, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Beta regression and boxplots", eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "model_simulations_from11750.R"))
model_performance_withmig$clim_hpv_sorensen.mean <- 1-model_performance_withmig$clim_hpv_sorensen.mean # dissimilarity

source(file.path(wd, "manuscript", "processing", "suppmat", "ordered_beta_regression_from11750.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "beta_regression_from11750.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "boxplot_performance_from11750.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "performance_from11750.R"))

```

```{r past_performance_from12000, fig.height = 120, fig.width = 190, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Beta regression and boxplots", eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "model_simulations_from12000.R"))
model_performance_withmig$clim_hpv_sorensen.mean <- 1-model_performance_withmig$clim_hpv_sorensen.mean # dissimilarity

source(file.path(wd, "manuscript", "processing", "suppmat", "ordered_beta_regression_from12000.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "beta_regression_from12000.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "boxplot_performance_from12000.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figS10", "performance_from12000.R"))

```

```{r figS10_past_performance_summary, fig.height = 240, fig.width = 180, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Performance of correlative models, fitted process-based models (inverse calibration using occurrence data) and expert process-based models (classical calibration).", eval = F}

# plot_grid(plot_grid(NULL, figS10_performance_wtime, NULL,
#                     labels = c("","a","") , 
#                     ncol = 3,
#                     rel_widths = c(0.2,0.6,0.2),
#                     label_fontfamily = "Helvetica Narrow", label_size = 11), 
#           figS10_performance_nomigration, 
#           figS10_performance_from11750, 
#           figS10_performance_from12000, 
#           get_legend(ordbetareg_plot),
#           ncol = 1, rel_heights = c(0.5, 0.5, 0.5, 0.5, 0.1))

plot_grid(plot_grid(figS10_performance_wtime, figS10_performance_TSS + theme(legend.position = "none"),
                    labels = c("a","b") ,
                    ncol = 2,
                    rel_widths = c(0.5,0.5), align = "hv", axis = "tblr",
                    label_fontfamily = "Helvetica Narrow", label_size = 11),
          figS10_performance_nomigration,
          figS10_performance_from11750,
          figS10_performance_from12000,
          get_legend(ordbetareg_plot),
          ncol = 1, rel_heights = c(0.5, 0.5, 0.5, 0.5, 0.1))


```





















